### ISSUE TITLE
POSIX not available on Windows enviroments

### ISSUE THREAD

**Issue by AshleyWrench** [Asana/php-asana#24]
when you try to get the system information with ``` posix_uname(); ``` (dispatcher.php line: 87) it cannot be run under a windows environment. This is because windows is POSIX non-compliant. So running your script on a windows server is impossible. 
I have personally found away around the issue by installing a linux environment (vagrant) on my windows PC, but for others this may be unavailable option - resulting in them not being able to create apps with asana. 
There is a windows alternative (probably the reason windows is non-compliant) called SUA - subsystem for unix based applications. If you change the script to check if ``` posix_uname() ``` is available, then you can send the system information depending on the OS (using posix_uname() for UNIX and SUA for windows). 

https://en.wikipedia.org/wiki/Windows_Services_for_UNIX - helpful link I suppose
http://php.net/manual/en/intro.posix.php - php.net saying that posix does not work on windows enviroments!

sorry I couldn't be much use, but I think issue could pop-up with some users and I personally had a hard time finding a solution! 

**NOTE**: I don't actually know what SUA is or dose, and I'm not 100% sure if you can access it through php. so my solution to fixing the script probably doesn't work.

**Comment by Buw** [comment]
Ok, found this - SUA is only available in windows 8 Enterprise Evaluation. And it would actually allow you to run POSIX functions (from what I can make out). The issue is that it is deprecated.
Here is the source for that info: http://superuser.com/questions/495360/does-windows-8-still-implement-posix 

Now for another solution for getting system information, it looks like you only need the os and the os_version. Unfortunately the only ways around I could find are a bit messy and don't really look like a reliable solution.

**Comment by epelz** [comment]
Hey there, thanks for bringing this up. We dug into this briefly, and agree that there don't seem to be very reliable and consistent solutions here. Some alternatives here may be:
- Using `php_uname('s')` and `php_uname('r') instead - http://php.net/manual/en/function.php-uname.php
- Use the Windows predefined constants - http://php.net/manual/en/info.constants.php
- Some combination of the above and `posix_uname`, potentially falling back to "unknown" for cases we cannot find the system information.

We're happy to review a pull request from you (or anyone else hitting this issue). Until then, we'll leave this issue open so that others who encounter this can chime in.

**Comment by adamhopkinson** [comment]
I'm having the same issue - posix_uname is undefined - running on Google App Engine. The following script fails:

```
require __DIR__ . '/vendor/autoload.php';
$client = Asana\Client::basicAuth(ASANA_API_KEY);
echo $client->users->me();
```

But `$projects = $client->projects->findAll();` works - I assume this doesn't call `posix_uname()`.

GAE is running PHP 5.6. I considered opening a new issue, but I believe a fix for checking if the function exists would solve the issue on GAE too.
