### ISSUE TITLE
Unable to connect:  35 SSL connect error

### ISSUE THREAD

**Issue by gbinow** [Asana/php-asana#39]
Hello guys. 
We're assembling a simple page with a list of our planned tasks so our users can follow our schedule. 
We were able to successfully use Asana API from localhost (no https). 
But when we try to use it from our production environment (https) we get the following error: 

Unable to connect to "https://app.asana.com/api/1.0/projects?limit=50&opt_fields=name%2Carchived&workspace=15777648238435": 35 SSL connect error

Would you have any clue about this?
Thank you very much :)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182694718843648/422883820761084)

**Comment by praecipula** [comment]
I'm suspecting that your server might be using TLS 1.0 or older (including any version of SSL). Due to security reasons we [turned off versions before TLS 1.0](https://asana.com/developers/feed/tls-10-shutoff).

We documented this a bit more fully, including how to determine if you're affected, in some of our other client libraries that seemed a bit more impacted, like [python-asana](https://github.com/Asana/python-asana#required-security-procedures-for-outdated-openssl-versions). Perhaps something there might give you a clue as to why you're having trouble connecting?

**Comment by gbinow** [comment]
You're absolutely right! Thank you very much! 

For future references, I used the following snippet to check my TLS version:

`$ch = curl_init('https://www.howsmyssl.com/a/check');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$data = curl_exec($ch);
curl_close($ch);

$json = json_decode($data);
echo $json->tls_version;`

**Comment by gbinow** [comment]
You're absolutely right! Thank you very much!

For future references, I used the following snippet to check my TLS version:

`$ch = curl_init('https://www.howsmyssl.com/a/check');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$data = curl_exec($ch);
curl_close($ch);

$json = json_decode($data);
echo $json->tls_version;`
