### ISSUE TITLE
Missing method to refresh token

### ISSUE THREAD

**Issue by andytruong** [Asana/php-asana#5]
We have `OAuthDispatcher::fetchToken($code)` but there's no `::refreshToken($refreshToken)`.

**Comment by noonhub** [comment]
We agree that this should be a method on the dispatcher and are prioritizing it's addition.

**Comment by noonhub** [comment]
This has been published in version `0.3.0` https://packagist.org/packages/asana/asana#v0.3.0 and an example of usage can be found https://github.com/Asana/php-asana/blob/master/examples/example-oauth.php

The library will also automatically refresh your access token when it has expired so that you don't have to manually call this method.
