### ISSUE TITLE
Getting tasks by Project ID and filtering by Tag or Section

### ISSUE THREAD

**Issue by cy-josh** [Asana/php-asana#52]
I'm trying to find out how I can get a certain set of tasks within a project. I've tried using sections and tags, but for some reason I'm not able to filter down properly.

This is what my request url looks like when I try to get all tasks, then filter by project and tag.
`https://app.asana.com/api/1.0/tasks?limit=50&project=708311468785908&tag=716726489964039`

Which returns this error:
`Must specify exactly one of project, tag, or assignee + workspace`

I've also tried getting all tasks within a project, then filter by tag. Same error as above.
`https://app.asana.com/api/1.0/projects/708311468785908/tasks?limit=50&tag=716726489964039`

It doesn't seem like it's currently possible to filter the response. Is it all or nothing? What am I missing? I can get this done by getting all tasks in a project, then looping through each to get their membership associations, but that's a pretty expensive query...

**Comment by praecipula** [comment]
Tags aren't one of the fields which we've indexed for querying for tasks, but projects are. You should be able to use https://app.asana.com/api/1.0/tasks?project=708311468785908 or https://app.asana.com/api/1.0/projects/708311468785908/tasks, but I believe the tag parameter will be ignored.

The set of parameters which are indexed and allow querying against are here under the GET /tasks example: https://asana.com/developers/api-reference/tasks#query - anything not in that list will require you to filter client-side.

You can use https://app.asana.com/api/1.0/sections/:section_id/tasks or https://app.asana.com/api/1.0/tasks?section=:section_id, but this will only work for boards view projects, and I see that the project with the ID you provided is a list project.

We will have another way to do queries shipping soon which will be *vastly* more capable, but it will only be available to premium and enterprize organizations, so that's something to look out for. Thanks!
